### ISSUE TITLE
Apps prompting for manual update in A13

### ISSUE THREAD

**Issue by rhynec** [NeoApplications/Neo-Store#367]
After testing silent updates on my Pixel 6a device running A13 (with apps targeting API 31 or higher), I've noticed that all such app updates will still bring up a manual update promp, while still installing silently in the background (i.e. canceling the manual prompt will still update the app).

This seems to be the double installation error that used to occur in the original F-Droid client, but I'm not sure. Silent updates still work properly in Droid-ify on my device.

**Comment by rhynec** [comment]
This is the behavior I mean. Android shouldn't be asking for permission to update, and it still occurs even if you ignore the dialog.

https://user-images.githubusercontent.com/86078431/212807656-1591e43b-1789-4599-8c61-540eb13c9d73.mp4

**Comment by rhynec** [comment]
This appears to have been fixed in version 0.9.13; I'll leave the issue open for now if anyone else would like to verify.

**Comment by xIUPITERx** [comment]
It's still happening.
https://user-images.githubusercontent.com/97352673/213865319-8c88ecb4-c15d-411e-9124-bbd8dff42213.mp4

**Comment by rhynec** [comment]
@xIUPITERx just tested again, and reinstalling the same version of an app does cause the pop-up to appear. However, could you try updating a higher version of an app instead? On my end, the bug doesn't occur in that situation.

My guess is that Android itself forces the pop-up to appear when trying to reinstall the same version of an app, but of course it could also be an edge case of the bug.

@machiav3lli perhaps it'd be better to disallow reinstalling the same version of an app by disabling the install button like in FDroid. It'd also make the Releases section a bit clearer.

**Comment by xIUPITERx** [comment]
> However, could you try updating a higher version of an app instead? On my end, the bug doesn't occur in that situation.

Yes, in that case it seems to be fixed.

> perhaps it'd be better to disallow reinstalling the same version of an app by disabling the install button like in FDroid. It'd also make the Releases section a bit clearer.

I don't think so, sometimes there is a bug due to an installation error and an update (even with the same version) can fix that without losing in-app data.

**Comment by machiav3lli** [comment]
Refer to [this](https://developer.android.com/reference/android/content/pm/PackageInstaller.SessionParams#setRequireUserAction(int)) to read the possible logic with A12's silent updates.

To make it clear, the system allows nothing such as silent install (except with root), but NS can update the apps that was installed (or lastly updated) by it, further more these apps should target at least sdk29/30 depending on your system.

More to that, 0.9.13 optimized handling of some install/update instances, so make sure to test considering what you know now. I'll close this, as the original issue is off.
