### ISSUE TITLE
Download notification persist after installation is finished

### ISSUE THREAD

**Issue by breversa** [NeoApplications/Neo-Store#444]
Hi!
First of all, I *love* Neo Store for the automatic update feature that was severely lacking in Aurora Droid! :D

However, the download notification sometimes doesn’t disappear once the download is finished and the installation done.

It displays e.g. "`Downloading openScale        6.3 MB / 6.3 MB`" but I cannot swipe it away.

If I expand the notification, the "Cancel" button appears but tapping on it does nothing.

The only way to clear that notification is to kill the Neo Store app (which I cannot do by long-pressing the Back button: https://github.com/NeoApplications/Neo-Store/issues/445).

Neo Store 0.9.15 from F-Droid

**Comment by eclairevoyant** [comment]
It should be swipeable? See #462. But that is still just a workaround.

The notification should just be cleared once install completes.

**Comment by il-santo** [comment]
Same problem for me. Even after completing an installation, the notification persists and most of the times is about a partial download still ongoing (obviously it's wrong).

**Comment by machiav3lli** [comment]
Should have been fixed on the latest alpha (get it from the community groups or TG channel) and report back.

**Comment by 48-mq** [comment]
I'm still seeing this bug on v 0.9.15

![Screenshot_20240315-110110](https://github.com/NeoApplications/Neo-Store/assets/145857730/183d6178-2634-4b37-8bb2-dedeed76fb56)
